# fly.toml app configuration file generated for mobile-gear-back on 2025-01-13T23:03:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mobile-gear-back'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
