# fly.toml app configuration file generated for mobilegear on 2023-07-07T00:44:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mobilegear"
primary_region = "eze"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
